repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-toml
  - id: requirements-txt-fixer
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.15.3
