---
- name: Provision the server
  hosts: localhost
  tags: always
  become: false

  tasks:
    - block:
      - name: Add the server to an inventory group
        add_host:
          name: "{% if lappland_server_ip == 'localhost' %}localhost{% else %}{{ lappland_server_ip }}{% endif %}"
          groups: vpn-host
          ansible_connection: "{% if lappland_server_ip == 'localhost' %}local{% else %}ssh{% endif %}"
          ansible_ssh_user: "{{ ssh_user }}"
          ansible_ssh_port: "{{ ssh_port }}"
          ansible_python_interpreter: "/usr/local/bin/python3"
          lappland_server_name: "{{ lappland_server_name }}"

      - name: Additional variables for the server
        add_host:
          name: "{{ lappland_server_ip }}"
          ansible_ssh_private_key_file: "{{ ssh_private_key_file }}"

      - name: Wait until SSH becomes ready...
        wait_for:
          port: "{{ ssh_port }}"
          host: "{{ lappland_server_ip }}"
          search_regex: "OpenSSH"
          delay: 10
          timeout: 320
          state: present

- name: Configure the server and install required software
  hosts: vpn-host
  gather_facts: true
  become: true
  tasks:
    - name: secret credentials included
      include_vars: secrets_credentials.yml

    - name: server configured
      block:
        - name: Wait until the infrastructure build and initialisation is complete
          wait_for:
            path: /var/log/lappland-result.json
            delay: 10
            timeout: 1200
            state: present
          become: false

        - name: register vio0 IP address
          shell: ifconfig vio0 | grep inet | awk '{print $2}'
          register: public_iface_address

        - name: register lo100 IP address
          shell: ifconfig lo100 | grep inet | awk '{print $2}'
          register: services_address

        - name: wireguard-configs role run
          import_role:
            name: wireguard-configs
          tags: wireguard-configs

        - name: wireguard-pf role run
          import_role:
            name: wireguard-pf
          tags: wireguard-pf

        - name: mail role run
          import_role:
            name: mail
          tags: mail

        - name: mail-sercer role run
          import_role:
            name: mail-server
          tags: mail-server

        - name: ids role run
          import_role:
            name: ids
          tags: ids

        - name: mfa role run
          import_role:
            name: mfa
          tags: mfa

        - name: monitoring role run
          import_role:
            name: monitoring
          tags: monitoring

        - name: hardening role run
          import_role:
            name: hardening
          tags: hardening
