---
- name: kern.bufcachepercent configured
  sysctl:
    name: kern.bufcachepercent
    value: '50'
    state: present
    reload: true

- name: net.inet.tcp.rfc3390 configured
  sysctl:
    name: net.inet.tcp.rfc3390
    value: '1'
    state: present
    reload: true

- name: net.inet.udp.recvspace configured
  sysctl:
    name: net.inet.udp.recvspace
    value: '262144'
    state: present
    reload: true

- name: net.inet.udp.sendspace configured
  sysctl:
    name: net.inet.udp.sendspace
    value: '262144'
    state: present
    reload: true

- name: net.inet.icmp.errppslimit configured
  sysctl:
    name: net.inet.icmp.errppslimit
    value: '1000'
    state: present
    reload: true

- name: net.inet.ipcomp.enable configured
  sysctl:
    name: net.inet.ipcomp.enable
    value: '1'
    state: present
    reload: true

- name: net.inet.tcp.mssdflt configured
  sysctl:
    name: net.inet.tcp.mssdflt
    value: '1440'
    state: present
    reload: false
