---
- name: Packages needed to build wgcf installed
  openbsd_pkg:
    name: go
    state: present

- name: wgcf repo cloned
  git:
    repo: https://github.com/ViRb3/wgcf.git
    dest: /root/git/wgcf

- name: Check for wgcf-profile.conf
  stat:
    path: /root/git/wgcf/wgcf-profile.conf
  register: wgcf_profile

- name: wgcf generate run
  shell: "cd /root/git/wgcf && go run main.go generate"
  when: wgcf_profile.exists == False

- name: Lappland Warp address registered
  shell: cat /root/git/wgcf/wgcf-profile.conf | grep Address | grep -Eo "([0-9]{1,3}\.){3}[0-9]{1,3}"
  register: warp_lappland_address
  when: wgcf_profile.exists == False

- name: Lappland Warp endpoint registered
  shell: cat /root/git/wgcf/wgcf-profile.conf | grep Endpoint | grep -Eo "([a-z]+\.)+[a-z]+"
  register: warp_lappland_endpoint

- name: Lappland Warp port registered
  shell: cat /root/git/wgcf/wgcf-profile.conf | grep Endpoint | grep -Eo "[0-9]{3,5}$"
  register: warp_wguard_port

- name: Lappland Warp public key registered
  shell: cat /root/git/wgcf/wgcf-profile.conf | grep PublicKey | grep -Eo "[a-zA-Z0-9+/=]{44}$"
  register: warp_wguard_public_key

- name: Lappland Warp private key registered
  shell: cat /root/git/wgcf/wgcf-profile.conf | grep PrivateKey | grep -Eo "[a-zA-Z0-9+/=]{44}$"
  register: warp_wguard_private_key

- name: Default gateway registered
  shell: route -n show -inet | grep default | awk '{print $2}'
  register: default_gateway
  ignore_errors: true

- name: Lappland Warp endpoint IP registered
  shell: dig +short "{{ warp_lappland_endpoint.stdout }}"
  register: warp_lappland_endpoint_ip
  ignore_errors: true

- name: hostname.wg10 for warp wireguard deployed
  template:
    src: hostname.wg10
    dest: /etc/
    owner: root
    group: wheel
    mode: 0640
    backup: no

- name: sysctl ipv4 forwarding enabled
  sysctl:
    name: net.inet.ip.forwarding
    value: '1'
    state: present
    reload: yes

- name: wg10 ingterface brought up
  shell: sh /etc/netstart wg10
  register: warpup
  ignore_errors: true
  changed_when: false
  check_mode: no

- name: pf.rules deployed
  template:
    src: pf.rules
    dest: /etc/pf.anchors/
    owner: root
    group: wheel
    mode: 0600
    backup: no
  notify:
    - restart pf

- name: Reload anchor
  shell: "/sbin/pfctl -a pf.rules -F Tables && /sbin/pfctl -a pf.rules -f /etc/pf.anchors/pf.rules"
  changed_when: false
  check_mode: no
