---
- name: Check mandatory variables are defined
  assert:
    that:
      - secret_gmail_email is defined
      - secret_gmail_secret is defined
  no_log: True

- name: mail server private key generated
  openssl_privatekey:
    path: /etc/ssl/private/smtp.gmail.com.key
    owner: root
    group: wheel
    mode: '0600'

- name: mail server certificates generated
  community.crypto.x509_certificate:
    path: /etc/ssl/smtp.gmail.com.crt
    privatekey_path: /etc/ssl/private/smtp.gmail.com.key
    provider: selfsigned
    owner: root
    group: wheel
    mode: '0600'
    selfsigned_not_after: "+365d"

- name: smtpd.conf deployed
  template:
    src: smtpd.conf
    dest: /etc/mail/
    owner: root
    group: wheel
    mode: '0644'
    backup: no
  notify:
    - restart smtpd

# - name: Check for secrets.db
#   shell: "ls /etc/mail/secrets.db"
#   register: secretsdb
#   ignore_errors: true
#   changed_when: false
#   check_mode: no

- name: OpenSMTP secrets deployed
  template:
    src: secrets
    dest: /etc/mail
    owner: root
    group: _smtpd
    mode: '0640'
    backup: no
  # when: "secretsdb.rc == 1"
  no_log: True
  notify:
    - restart smtpd

- name: Checked for existing secrets.db
  stat:
    path: /etc/mail/secrets.db
  register: secrets_db

- name: Existing secrets.db backed up
  copy:
    src: /etc/mail/secrets.db
    dest: /etc/mail/secrets.db.{{ ansible_date_time.iso8601_basic_short}}
  when: secrets_db.stat.exists == True

- name: secrets db created
  shell: "cd /etc/mail && /usr/sbin/makemap secrets"
  args:
    creates: /etc/mail/secrets.db
  # when: "secretsdb.rc == 1"
  notify:
    - restart smtpd

- name: secrets file removed
  file:
    state: absent
    path: /etc/mail/secrets

- name: OpenSMTP aliases deployed
  template:
    src: aliases
    dest: /etc/mail/
    owner: root
    group: wheel
    mode: '0644'
    backup: no
  notify:
    - restart smtpd

- name: newaliases run
  shell: /usr/bin/newaliases
  ignore_errors: true
  changed_when: false
  check_mode: no
