- name: enable monitoring daemons
  service:
    name: "{{ item }}"
    enabled: true
  loop:
    - prometheus
    - node_exporter
    - grafana

- name: start monitoring daemons
  service:
    name: "{{ item }}"
    state: started
  loop:
    - prometheus
    - node_exporter
    - grafana
